string address          # MAC address of access point
string ssid             # SSID of network
uint8 signal            # Signal strengh /100
bool encryption         # If network is encrypted
float32 frequency       # Frequency of channel in GHz
string security         # Security Used (ex.: WEP/WPA)
string groupCipher      # Group cipher protocol (ex.: CCMP)
string pairwiseCiphers  # Pairwire cipher protocol (ex.: CCMP)
string protocol         # WiFi protocol used (ex.: IEEE 802.11bgn)
